### ISSUE TITLE
See my Fault?

### ISSUE THREAD

**Issue by thebrain2015** [Clansuite/Clansuite#20]
Warning: require(/users/thebrain2015/www/vendor/ksst/kf/framework/Koch/Exception/Exception.php) [function.require]: failed to open stream: No such file or directory in /users/thebrain2015/www/Installation/bootstrap.php on line 62

Fatal error: require() [function.require]: Failed opening required '/users/thebrain2015/www/vendor/ksst/kf/framework/Koch/Exception/Exception.php' (include_path='.') in /users/thebrain2015/www/Installation/bootstrap.php on line 62

**Comment by jakoch** [comment]
I think you forgot to run `composer install` to fetch the framework as a dependency.
After that you will run into other errors, because the system is in a bad shape.
Keep me updated...
